// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQD8WhOII4UWacCQNhEiHk7m91sx_SJII',
    appId: '1:882274344569:web:a06548b7355f91be057ea8',
    messagingSenderId: '882274344569',
    projectId: 'stokopname-9b20e',
    authDomain: 'stokopname-9b20e.firebaseapp.com',
    storageBucket: 'stokopname-9b20e.firebasestorage.app',
    measurementId: 'G-3PHE8M73RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQMmo3NDZSPeM3j6be5hF1zKbaZB7kvco',
    appId: '1:882274344569:android:df0bb683eb9f6cb7057ea8',
    messagingSenderId: '882274344569',
    projectId: 'stokopname-9b20e',
    storageBucket: 'stokopname-9b20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe7CQiUE8HttKDKoBNjACo12_308cUHd8',
    appId: '1:882274344569:ios:15197589ae3b9bcd057ea8',
    messagingSenderId: '882274344569',
    projectId: 'stokopname-9b20e',
    storageBucket: 'stokopname-9b20e.firebasestorage.app',
    iosBundleId: 'com.example.stokopBarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe7CQiUE8HttKDKoBNjACo12_308cUHd8',
    appId: '1:882274344569:ios:15197589ae3b9bcd057ea8',
    messagingSenderId: '882274344569',
    projectId: 'stokopname-9b20e',
    storageBucket: 'stokopname-9b20e.firebasestorage.app',
    iosBundleId: 'com.example.stokopBarang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQD8WhOII4UWacCQNhEiHk7m91sx_SJII',
    appId: '1:882274344569:web:7ca350cc8617feed057ea8',
    messagingSenderId: '882274344569',
    projectId: 'stokopname-9b20e',
    authDomain: 'stokopname-9b20e.firebaseapp.com',
    storageBucket: 'stokopname-9b20e.firebasestorage.app',
    measurementId: 'G-PSTMZMTEMK',
  );
}
